### ISSUE TITLE
post-processed Data?

### ISSUE THREAD

**Issue by HeJunhong1107** [chemosim-lab/M2OR#2]
Hello,

Thank you for making the M2OR database available; it has been instrumental in the development of GPCRs. However, I've observed that the download link on your official website is currently inactive, and the data in this repository seems to be missing some information.

Could you kindly provide an alternative method or link to access the complete, post-processed data? I eagerly await your response.

**Comment by Samarak99** [comment]
Hello, 

Thank you for you comment. I would need more information about the issue in order to fix it. What link have you tried to use and what was the exact error that happened.

Thank you again for your interest in our database.
M2OR Team

**Comment by HeJunhong1107** [comment]
Thank you for your response. I have identified several issues:
1. The download link at https://m2or.chemsensim.fr/experiments appears to be non-functional.

![M2OR](https://github.com/chemosim-lab/M2OR/assets/126778402/4408bcc9-c2db-4501-99e4-ff6fae2c309c)

2. The data in the 'M2OR_20230428.csv' file seems to overlook the chirality information of the compounds, leading to some discrepancies. For instance:

![M2OR_issue](https://github.com/chemosim-lab/M2OR/assets/126778402/af75ba55-213f-4bbe-94fe-05844a5399f6)

The compound pointed to by CAS-ID 80-54-6 is Lilial instead of 3-(4-tert-butylphenyl)butanal.

**Comment by Samarak99** [comment]
Okay well received, we will check them and get back to you!

**Comment by MatejHl** [comment]
Hello @HeJunhong1107,

I'm happy that M2OR is helping a fellow scientist!

We checked the molecule you mentioned and the name and InChI Key are actually correct. The molecule used in the paper is **lilyall** (3-(4-tert-butylphenyl)butanal), which is a different compound than **lilial**. However, there is a common confusion between the two (e.g. ScenTree is considering them as synonyms) and so the CAS of lilial was parsed. We will update the information in the next release of the data.

Generally speaking, InChI Key is the main identifier of molecules and it is curated. Other identifiers like CAS are non-unique and may not even exist, so they are there just as an additional information and I highly recommend avoiding them in any bulk data processing.

As for the download of the preprocessed data, we are working on the issue. It turned out to be more complicated to fix than it looks, so we will let you know when it is finished. In the mean time, you can access the preprocessed data here (it take a second or two to load):

https://m2or.chemsensim.fr/advanced-search?_token=335PpzJkmTPZ7p9xULn400OWYwM4qMOCYXQCYhom&conditions%5B%5D=and&tables%5B%5D=inchi_key&values%5B%5D=&conditions%5B%5D=and&tables%5B%5D=uniprot_id&values%5B%5D=&conditions%5B%5D=and&tables%5B%5D=co_transfection&values%5B%5D=&conditions%5B%5D=and&tables%5B%5D=sequence&values%5B%5D=

Best,
     Matej

**Comment by HeJunhong1107** [comment]
Dear Matej, 

Thank you once again for your kind response. Over the past few days, I have made efforts to supplement and modify the relevant data in 'M2OR_20230428.csv.' This primarily involved:

1. Retrieving compound-specific standard information, including CAS-ID, based on Inchikey and PubChem REST API.
2. Retrieving protein sequence-related information based on Uniprot-ID.
3. Standardizing gene names.

Here are the results after my personal processing, and I hope they prove helpful to your team or other researchers with future needs.

[M2OR_240201_revised.xlsx](https://github.com/chemosim-lab/M2OR/files/14133765/M2OR_240201_revised.xlsx)

**Comment by MatejHl** [comment]
As the website and the preprocessed data is up and running, I'm closing the issue. 

Thank you HeJunhong1107 and if you how other suggestions, please don't hesitate to let us know.
